[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Disable edition shaders for cine cards (they mess up purchase animation)
[[patches]]
[patches.regex]
target = '=[SMODS _ "src/card_draw.lua"]'
pattern = '''(?<indent>[\t ]*)(?<cond>if self\.edition then)(?<post>\n[\t ]*for k, v in pairs\(G\.P_CENTER_POOLS\.Edition\) do\n[\t ]*if self\.edition\[v\.key:sub\(3\)\] and v\.shader then)'''
position = "at"
line_prepend = "$indent"
payload = '''
    if self.edition and not Reverie.is_cine_or_reverie(self) then
        $post
'''

# Disable edition shaders for cine cards (they mess up purchase animation)
[[patches]]
[patches.regex]
target = '=[SMODS _ "src/card_draw.lua"]'
pattern = '''(?<indent>[\t ]*)if \(self\.edition and self\.edition\.negative\)(?<post>.*)'''
position = "at"
line_prepend = "$indent"
payload = '''
if (self.edition and self.edition.negative and not Reverie.is_cine_or_reverie(self))$post
'''